version: '3.8'

services:
  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      - SERVER_PORT=50051
      - APP_LOGTOFILE=false
